-- 0. Tao co so du lieu
USE master
IF EXISTS (SELECT * FROM sys.sysdatabases WHERE name = 'ASM2_FX09444')
	DROP DATABASE ASM2_FX09444;
GO

CREATE DATABASE ASM2_FX09444
GO

-- 0. Su dung co so du lieu
USE ASM2_FX09444
GO

--1. Bang chu de
CREATE TABLE CHUDE
(
  CHUDE_ID VARCHAR(20) NOT NULL,
  CDE_TEN NVARCHAR(255) NOT NULL,

  PRIMARY KEY (CHUDE_ID)
);
GO

--2. Bang quyen quan ly
CREATE TABLE QUYENQUANLY
(
  QUYENQUANLY_ID VARCHAR(20) NOT NULL,
  QQL_TEN NVARCHAR(255) NOT NULL,
  QQL_XEM BIT NOT NULL  DEFAULT 'FALSE',
  QQL_THEM BIT NOT NULL DEFAULT 'FALSE',
  QQL_SUA BIT NOT NULL DEFAULT 'FALSE',
  QQL_XOA BIT NOT NULL DEFAULT 'FALSE',
  QQL_CAPQUYEN BIT NOT NULL DEFAULT 'FALSE',

  PRIMARY KEY (QUYENQUANLY_ID)
);
GO

--3. Bang quyen
CREATE TABLE QUYEN
(
  QUYEN_ID VARCHAR(20) NOT NULL,
  QUN_TEN NVARCHAR(255) NOT NULL,
  QUN_XEM BIT NOT NULL DEFAULT  'FALSE',
  QUN_THEM BIT NOT NULL DEFAULT 'FALSE',
  QUN_XOA BIT NOT NULL DEFAULT 'FALSE',
  QUN_SUA BIT NOT NULL DEFAULT 'FALSE',
  
  CONSTRAINT PK_QUYEN PRIMARY KEY (QUYEN_ID),

  QUYENQUANLY_ID VARCHAR(20), -- khoa ngoai
  CONSTRAINT FK_QUYEN_QUYENQUANLY FOREIGN KEY (QUYENQUANLY_ID) REFERENCES QUYENQUANLY(QUYENQUANLY_ID)
);
GO

-- 4. Bang bien tap vien
CREATE TABLE BIENTAPVIEN
(
  BIENTAPVIEN_ID VARCHAR(20) NOT NULL,
  BTV_TEN NVARCHAR(255) NOT NULL,
  BTV_EMAIL NVARCHAR(255) NOT NULL,
  BTV_PASS NVARCHAR(255) NOT NULL,
  BTV_LUONG MONEY DEFAULT 0,

  PRIMARY KEY (BIENTAPVIEN_ID),

  QUYEN_ID VARCHAR(20), -- khoa ngoai
  CONSTRAINT FK_BIENTAPVIEN_QUYEN FOREIGN KEY (QUYEN_ID) REFERENCES QUYEN(QUYEN_ID),

  UNIQUE (BTV_EMAIL),
  CHECK (BTV_LUONG < 2000) -- luong phai nho hon 2000
);
GO

-- 5. Bang phong vien
CREATE TABLE PHONGVIEN
(
  PHONGVIEN_ID VARCHAR(20) NOT NULL,
  PVN_TEN NVARCHAR(255) NOT NULL,
  PVN_EMAIL NVARCHAR(255) NOT NULL,
  PVN_PASS NVARCHAR(255) NOT NULL,
  PVN_LUONG MONEY DEFAULT 0,

  PRIMARY KEY (PHONGVIEN_ID),

  QUYEN_ID VARCHAR(20), -- khoa ngoai
  BIENTAPVIEN_ID VARCHAR(20) NOT NULL, -- khoa ngoai
  CONSTRAINT FK_PHONGVIEN_QUYEN FOREIGN KEY (QUYEN_ID) REFERENCES QUYEN(QUYEN_ID),
  CONSTRAINT FK_PHONGVIEN_BIENTAPVIEN FOREIGN KEY (BIENTAPVIEN_ID) REFERENCES BIENTAPVIEN(BIENTAPVIEN_ID),
  
  UNIQUE (PVN_EMAIL),
  CHECK (PVN_LUONG < 1000) -- luong nho hon 100
);
GO

-- 6. Bang bai bao
CREATE TABLE BAIBAO
(
  BAIBAO_ID VARCHAR(20) NOT NULL,
  BBO_TRANGTHAI BIT NOT NULL DEFAULT 'FALSE',
  BBO_NGAYVIET DATE NOT NULL,
  BBO_NGAYDANG DATE DEFAULT NULL,
  BBO_TEN NVARCHAR(255) NOT NULL,
  BBO_NOIDUNG NVARCHAR(MAX) NOT NULL,

  PRIMARY KEY (BAIBAO_ID),

  -- khoa ngoai
  PHONGVIEN_ID VARCHAR(20) NOT NULL, 
  BIENTAPVIEN_ID VARCHAR(20) NOT NULL,
  CHUDE_ID VARCHAR(20) NOT NULL,
  -- rang buoc voi bang khac
  CONSTRAINT FK_BAIBAO_PHONGVIEN FOREIGN KEY (PHONGVIEN_ID) REFERENCES PHONGVIEN(PHONGVIEN_ID),
  CONSTRAINT FK_BAIBAO_BIENTAPVIEN FOREIGN KEY (BIENTAPVIEN_ID) REFERENCES BIENTAPVIEN(BIENTAPVIEN_ID),
  CONSTRAINT FK_BAIBAO_CHUDE FOREIGN KEY (CHUDE_ID) REFERENCES CHUDE(CHUDE_ID)
);

