USE ASM2_FX09444
GO
SELECT * FROM BAIBAO WHERE BAIBAO_ID = 'BBO015';

BEGIN TRANSACTION
-- Cap nhat (trang thai, thoi gian duyet) cho bai bao chua duyet
UPDATE BAIBAO
SET BBO_TRANGTHAI = 1, BBO_NGAYDANG = GETDATE()
WHERE BAIBAO_ID = 'BBO015'

SELECT * FROM BAIBAO WHERE BAIBAO_ID = 'BBO015';
ROLLBACK TRANSACTION