USE ASM2_FX09444
GO 

--1. Truy van 10 bai bao moi nhat
SELECT TOP(10) * FROM BAIBAO 
WHERE BBO_TRANGTHAI = 1
ORDER BY BBO_NGAYDANG DESC;
GO

-- 3. Truy van su dung like
SELECT * FROM BAIBAO
WHERE BBO_TEN LIKE '%nga%'
GO

-- 4. Truy van co lien quan den dieu kien ve thoi gian
SELECT * FROM BAIBAO
WHERE DATEPART(MONTH, BBO_NGAYDANG) = 4 AND DATEPART(DAY, BBO_NGAYDANG) >10;
GO

-- 5. Truy van nhieu bang su dung inner join
SELECT B.BAIBAO_ID,B.BBO_TEN, C.CDE_TEN 
FROM BAIBAO AS B
JOIN CHUDE AS C ON C.CHUDE_ID = B.CHUDE_ID
ORDER BY C.CDE_TEN
GO

-- 6. Truy van su dung Self join (join cung mot bang)
SELECT P1.PHONGVIEN_ID, P1.PVN_LUONG, P2.PVN_TEN, P2.PVN_LUONG
FROM PHONGVIEN P1, PHONGVIEN P2
WHERE P1.PVN_LUONG < P2.PVN_LUONG 
ORDER BY P1.PVN_LUONG
GO

-- 7. Truy van su dung outer join (full join)
SELECT P.PHONGVIEN_ID, P.PVN_TEN, B.BBO_TEN
FROM PHONGVIEN AS P
FULL JOIN BAIBAO AS B ON P.PHONGVIEN_ID = B.PHONGVIEN_ID
ORDER BY P.PHONGVIEN_ID
GO

---- 8. Truy van su dung truy van con
SELECT * 
FROM PHONGVIEN
WHERE PVN_LUONG = (SELECT MAX(PVN_LUONG) FROM PHONGVIEN)
GO

SELECT * 
FROM (SELECT PHONGVIEN_ID, PVN_TEN FROM PHONGVIEN ) AS PV
GO

SELECT P.PHONGVIEN_ID, P.PVN_TEN, (SELECT B.BTV_TEN  FROM BIENTAPVIEN B WHERE P.BIENTAPVIEN_ID = B.BIENTAPVIEN_ID) AS BTV_TEN
FROM PHONGVIEN P
GO

-- 8. Truy van su dung WITH
WITH 
PV AS 
(SELECT PHONGVIEN_ID, PVN_TEN, BIENTAPVIEN_ID FROM PHONGVIEN),
BTV AS
(SELECT BIENTAPVIEN_ID, BTV_TEN FROM BIENTAPVIEN)

SELECT * 
FROM PV P
JOIN BTV B ON P.BIENTAPVIEN_ID = B.BIENTAPVIEN_ID
ORDER BY P.PHONGVIEN_ID
GO

-- 9. Truy van su dung having: So bai bao cua moi phong vien
SELECT PHONGVIEN_ID, COUNT (BAIBAO_ID) AS SOBAI_MOI_PHONGVIEN
FROM BAIBAO
GROUP BY PHONGVIEN_ID
HAVING COUNT(BAIBAO_ID) >=3
ORDER BY SOBAI_MOI_PHONGVIEN DESC;
GO

-- 10. Truy van su dung ham
SELECT * FROM SYS.objects
WHERE name LIKE 'FC%'
ORDER BY create_date DESC
GO

SELECT * FROM dbo.fc_top_baibao (5); -- top bai bao moi dang

SELECT * FROM dbo.fc_thongke_phongvien_theo_luong (900); -- nhan vien co luong tu 900

SELECT B.BAIBAO_ID, B.BBO_TEN, B.BBO_TRANGTHAI, dbo.fc_trang_thai(B.BAIBAO_ID) AS TRANGTHAI_CHITIET
FROM BAIBAO B 
ORDER BY BAIBAO_ID;
GO
